Metrics/LineLength:
  Max: 9999
Metrics/BlockLength:
  Max: 9999
Metrics/MethodLength:
  Max: 9999
AllCops:
  Exclude:
    - 'app/views/**/*'
# controller need to use `and return` to make sure
# api do not look for template but just render json
Style/AndOr:
  Exclude:
    - 'app/controllers/**/*'
