version: '3.0'

services:
  app:
    image: "${ECR_URL}/${PROJECT_NAME}_app"
    logging:
      driver: awslogs
      options: 
        awslogs-group: "${PROJECT_NAME}"
        awslogs-region: "${AWS_REGION}"
        awslogs-stream-prefix: app
  web:
    image: "${ECR_URL}/${PROJECT_NAME}_web"
    logging:
      driver: awslogs
      options: 
        awslogs-group: "${PROJECT_NAME}"
        awslogs-region: "${AWS_REGION}"
        awslogs-stream-prefix: web

# more awslogs driver options here
# https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html#create_awslogs_logdriver_options
