version: '3.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    environment:
      - RAILS_MASTER_KEY
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    links:
      - app
    depends_on:
      - app
    ports:
      - 80:80
