version: '3.0'

services:
  app:
    image: "${ECR_URL}/${PROJECT_NAME}_app"
    build:
      context: .
      dockerfile: Dockerfile_app
    environment:
      RAILS_MASTER_KEY: "${RAILS_MASTER_KEY}"
    # logging:
    #   driver: awslogs
    #   options: 
    #     awslogs-group: "${PROJECT_NAME}"
    #     awslogs-region: ap-southeast-1
    #     awslogs-stream-prefix: app
  web:
    image: "${ECR_URL}/${PROJECT_NAME}_web"
    build:
      context: .
      dockerfile: Dockerfile_web
    links:
      - app
    depends_on:
      - app
    ports:
      - 80:80
    # logging:
    #   driver: awslogs
    #   options: 
    #     awslogs-group: "${PROJECT_NAME}"
    #     awslogs-region: ap-southeast-1
    #     awslogs-stream-prefix: web
