default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  variables:
    sql_mode: TRADITIONAL

development:
  <<: *default
  username: root
  password: password
  socket: /tmp/mysql.sock
  database: <%= Rails.application.class.module_parent_name.downcase %>_development

test:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  adapter: sqlite3
  database: db/test.sqlite3

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
